In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df = pd.read_csv('Train.csv')
df.head()

,ID,zone,gender,deathdate,age,avg_temperature,max_temperature,min_temperature,precipitation,latitude,longitude,location,is_climate_sensitive
0,ID_1FE951BD,Rural,Male,2007-10-02,30.0,21.137037,25.569017,18.451642,0.951601,0.584646,33.546344,"Izimba, Iganga, Uganda",1
1,ID_5927A443,Rural,Male,2008-01-05,2.0,24.062790,29.312026,18.977212,0.053352,0.549565,33.490326,"Nawanzu, Iganga, Uganda",1
2,ID_C4E67025,Rural,Female,2008-02-14,31.0,22.407868,26.746058,18.112977,0.090349,0.573420,33.483655,"Buluza, Iganga, Uganda",1
3,ID_44DC5CE9,Rural,Female,2008-02-15,1.0,23.315198,28.056889,18.955708,0.286814,0.549565,33.490326,"Nawanzu, Iganga, Uganda",1
4,ID_33C677BB,Rural,Female,2008-02-15,69.0,23.315198,28.056889,18.955708,0.286814,1.072343,34.226647,"Magada, Mbale City, Bugisa sub-region, Eastern...",0

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Zone'] = le.fit_transform(df['zone'])
df.drop('zone', axis=1, inplace=True)
df['Gender'] = le.fit_transform(df['gender'])
df.drop('gender', axis=1, inplace=True)
df.drop('location', axis=1, inplace=True)
df.drop('ID', axis=1, inplace=True)
df.drop('deathdate', axis=1, inplace=True)
df

,age,avg_temperature,max_temperature,min_temperature,precipitation,latitude,longitude,is_climate_sensitive,Zone,Gender
0,30.0,21.137037,25.569017,18.451642,0.951601,0.584646,33.546344,1,1,1
1,2.0,24.062790,29.312026,18.977212,0.053352,0.549565,33.490326,1,1,1
2,31.0,22.407868,26.746058,18.112977,0.090349,0.573420,33.483655,1,1,0
3,1.0,23.315198,28.056889,18.955708,0.286814,0.549565,33.490326,1,1,0
4,69.0,23.315198,28.056889,18.955708,0.286814,1.072343,34.226647,0,1,0
...,...,...,...,...,...,...,...,...,...,...
3141,92.0,21.869711,24.824496,19.501874,4.250624,0.572884,33.506221,0,1,0
3142,0.0,21.957913,25.210808,19.286763,4.133601,0.614154,33.483544,1,0,1
3143,0.0,22.436613,26.813967,18.726832,1.473170,0.550000,33.450000,0,1,0
3144,0.0,22.445975,25.554302,19.487528,1.220220,0.728530,33.468347,1,0,1
3145,0.0,20.017494,22.453402,18.545574,3.536480,0.591526,33.509251,0,1,0

In [35]:
from sklearn.cluster import KMeans


coords = df[['latitude', 'longitude']]
kmeans = KMeans(n_clusters=8, random_state=42, n_init=10)

df['geo_cluster'] = kmeans.fit_predict(coords)
df

,age,avg_temperature,max_temperature,min_temperature,precipitation,latitude,longitude,is_climate_sensitive,Zone,Gender,geo_cluster
0,30.0,21.137037,25.569017,18.451642,0.951601,0.584646,33.546344,1,1,1,4
1,2.0,24.062790,29.312026,18.977212,0.053352,0.549565,33.490326,1,1,1,0
2,31.0,22.407868,26.746058,18.112977,0.090349,0.573420,33.483655,1,1,0,0
3,1.0,23.315198,28.056889,18.955708,0.286814,0.549565,33.490326,1,1,0,0
4,69.0,23.315198,28.056889,18.955708,0.286814,1.072343,34.226647,0,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...
3141,92.0,21.869711,24.824496,19.501874,4.250624,0.572884,33.506221,0,1,0,4
3142,0.0,21.957913,25.210808,19.286763,4.133601,0.614154,33.483544,1,0,1,7
3143,0.0,22.436613,26.813967,18.726832,1.473170,0.550000,33.450000,0,1,0,0
3144,0.0,22.445975,25.554302,19.487528,1.220220,0.728530,33.468347,1,0,1,5
3145,0.0,20.017494,22.453402,18.545574,3.536480,0.591526,33.509251,0,1,0,4

In [36]:
df['temp_range'] = df['max_temperature'] - df['min_temperature']
df.drop(columns=['max_temperature', 'min_temperature'], inplace=True)

df

,age,avg_temperature,precipitation,latitude,longitude,is_climate_sensitive,Zone,Gender,geo_cluster,temp_range
0,30.0,21.137037,0.951601,0.584646,33.546344,1,1,1,4,7.117375
1,2.0,24.062790,0.053352,0.549565,33.490326,1,1,1,0,10.334814
2,31.0,22.407868,0.090349,0.573420,33.483655,1,1,0,0,8.633080
3,1.0,23.315198,0.286814,0.549565,33.490326,1,1,0,0,9.101181
4,69.0,23.315198,0.286814,1.072343,34.226647,0,1,0,2,9.101181
...,...,...,...,...,...,...,...,...,...,...
3141,92.0,21.869711,4.250624,0.572884,33.506221,0,1,0,4,5.322622
3142,0.0,21.957913,4.133601,0.614154,33.483544,1,0,1,7,5.924045
3143,0.0,22.436613,1.473170,0.550000,33.450000,0,1,0,0,8.087135
3144,0.0,22.445975,1.220220,0.728530,33.468347,1,0,1,5,6.066774
3145,0.0,20.017494,3.536480,0.591526,33.509251,0,1,0,4,3.907828

In [37]:
df.columns

Index(['age', 'avg_temperature', 'precipitation', 'latitude', 'longitude',
       'is_climate_sensitive', 'Zone', 'Gender', 'geo_cluster', 'temp_range'],
      dtype='str')

In [38]:
df['heat_stress_index'] = df['avg_temperature'] * df['precipitation']

df['temp_zone_anomaly'] = df['avg_temperature'] - df.groupby('Zone')['avg_temperature'].transform('mean')
df['precip_zone_anomaly'] = df['precipitation'] - df.groupby('Zone')['precipitation'].transform('mean')

df['age_temp_interaction'] = df['age'] * df['avg_temperature']
df

,age,avg_temperature,precipitation,latitude,longitude,is_climate_sensitive,Zone,Gender,geo_cluster,temp_range,heat_stress_index,temp_zone_anomaly,precip_zone_anomaly,age_temp_interaction
0,30.0,21.137037,0.951601,0.584646,33.546344,1,1,1,4,7.117375,20.114028,-0.939611,-0.564927,634.111113
1,2.0,24.062790,0.053352,0.549565,33.490326,1,1,1,0,10.334814,1.283804,1.986142,-1.463175,48.125579
2,31.0,22.407868,0.090349,0.573420,33.483655,1,1,0,0,8.633080,2.024538,0.331220,-1.426178,694.643896
3,1.0,23.315198,0.286814,0.549565,33.490326,1,1,0,0,9.101181,6.687135,1.238551,-1.229713,23.315198
4,69.0,23.315198,0.286814,1.072343,34.226647,0,1,0,2,9.101181,6.687135,1.238551,-1.229713,1608.748683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3141,92.0,21.869711,4.250624,0.572884,33.506221,0,1,0,4,5.322622,92.959926,-0.206937,2.734097,2012.013366
3142,0.0,21.957913,4.133601,0.614154,33.483544,1,0,1,7,5.924045,90.765242,-0.091651,2.608018,0.000000
3143,0.0,22.436613,1.473170,0.550000,33.450000,0,1,0,0,8.087135,33.052934,0.359965,-0.043358,0.000000
3144,0.0,22.445975,1.220220,0.728530,33.468347,1,0,1,5,6.066774,27.389029,0.396412,-0.305362,0.000000
3145,0.0,20.017494,3.536480,0.591526,33.509251,0,1,0,4,3.907828,70.791471,-2.059153,2.019953,0.000000

In [39]:
X = df.drop(columns=['is_climate_sensitive'])
y = df['is_climate_sensitive']

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42, 
    stratify=y
)

In [41]:
import xgboost as xgb

# Handle target imbalance
scale_pos_weight = (len(y_train) - sum(y_train)) / sum(y_train)

model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.03,
    max_depth=6,
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

model.fit(X_train, y_train)

# Predict probabilities (NOT hard 0/1 predictions)
val_probs = model.predict_proba(X_val)[:, 1]

In [42]:
import numpy as np
from sklearn.metrics import f1_score, roc_auc_score

best_thresh = 0.5
best_f1 = 0.0

for thresh in np.arange(0.1, 0.9, 0.01):
    preds = (val_probs >= thresh).astype(int)
    score = f1_score(y_val, preds)
    if score > best_f1:
        best_f1 = score
        best_thresh = thresh

print(f"ROC-AUC Score: {roc_auc_score(y_val, val_probs):.4f}")
print(f"Optimal Threshold: {best_thresh:.2f}")
print(f"New F1 Score: {best_f1:.4f}")

ROC-AUC Score: 0.7551
Optimal Threshold: 0.25
New F1 Score: 0.8072